# Generated by Django 3.0.5 on 2020-06-22 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myauth', '0003_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40)),
                ('more', models.CharField(default='Отсутствует', max_length=200)),
                ('image', models.CharField(default='https://www.salonlfc.com/wp-content/uploads/2018/01/image-not-found-scaled-1150x647.png', max_length=150)),
                ('address', models.CharField(default='Отсутствует', max_length=100)),
                ('price', models.CharField(default='Отсутствует', max_length=40)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myauth.User')),
            ],
        ),
    ]
