# Generated by Django 3.0.5 on 2020-06-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40)),
                ('more', models.CharField(default='Отсутствует', max_length=200)),
                ('image', models.CharField(default='https://www.salonlfc.com/wp-content/uploads/2018/01/image-not-found-scaled-1150x647.png', max_length=150)),
                ('address', models.CharField(default='Отсутствует', max_length=100)),
                ('price', models.CharField(default='Отсутствует', max_length=40)),
            ],
        ),
    ]
