# Generated by Django 3.0.5 on 2020-06-23 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20200622_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='by',
        ),
    ]
